### ISSUE TITLE
Add licenses to Amusewiki documentation

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki-site#21]
Markup manual is based on Emacs Muse documentation and is licensed under GFDL, but for other documentation there is no license.

As documentation for Amusewiki is managed here, it makes sense to add license information at least to `install.muse`, `roles.muse`, `remote-syncing.muse`, `offline-tools.muse` and other files which document Amusewiki itself and are not presentations or blog posts.

I would suggest CC-BY-SA or CC0 or maybe the same license as Amusewiki itself (POD documentation is licensed this way already).

**Comment by melmothx** [comment]
I'm not entirely sure if I need to edit each file or adding a fixed string like 
"Except where otherwise noted, content on this site is licensed under a Creative Commons ...". There's a slot missing in the template though, it should go really down into the footer.

**Comment by link2xt** [comment]
With systemd, users can run these services with `loginctl enable-linger` using similar unit files.

**Comment by melmothx** [comment]
@link2xt Please checkout https://amusewiki.org (fallback license in the site footer) and in the readme. I guess I can close this issue?

**Comment by link2xt** [comment]
Yes, that looks good
